import streamlit as st
from snowflake.snowpark.context import get_active_session

# --------------------------------------------------
# Page config
# --------------------------------------------------
st.set_page_config(
    page_title="Gold Layer (L3) – Agentic SQL Builder",
    page_icon="🤖",
    layout="wide"
)

# --------------------------------------------------
# Snowflake session
# --------------------------------------------------
session = get_active_session()

# --------------------------------------------------
# Header
# --------------------------------------------------
st.markdown("""
<div style="background:linear-gradient(90deg,#FF3621,#E8590C);
padding:1.5rem;border-radius:8px;color:white">
<h2>🤖 Gold Layer (L3) – Agentic SQL Builder</h2>
<p>Snowflake Demo | Natural Language → Analytical Views</p>
</div>
""", unsafe_allow_html=True)

# --------------------------------------------------
# Sidebar – Configuration
# --------------------------------------------------
with st.sidebar:
    st.header("Configuration")

    warehouse = st.text_input("Warehouse", "COMPUTE_WH", disabled=True)
    database = st.text_input("Database", "DEV_DB", disabled=True)

    l2_schema = st.text_input("Source Schema (L2)", "L2")
    l3_schema = st.text_input("Target Schema (L3)", "L3")

    st.markdown("---")
    st.caption("L2 tables must already exist")

# --------------------------------------------------
# Ensure L3 schema exists
# --------------------------------------------------
session.sql(f"CREATE SCHEMA IF NOT EXISTS {database}.{l3_schema}").collect()

# --------------------------------------------------
# Helper: fetch L2 tables
# --------------------------------------------------
def get_l2_tables():
    q = f"""
    SELECT table_name
    FROM {database}.information_schema.tables
    WHERE table_schema = '{l2_schema}'
    """
    return [r["TABLE_NAME"] for r in session.sql(q).collect()]

l2_tables = get_l2_tables()

# --------------------------------------------------
# Main UI
# --------------------------------------------------
col_chat, col_sql = st.columns([3, 2])

# ============================
# LEFT: Agent Chat (Demo)
# ============================
with col_chat:
    st.markdown("### 💬 Describe your analytical requirement")

    user_prompt = st.text_area(
        "Example: Total revenue by customer and month",
        height=120
    )

    if st.button("🚀 Generate SQL", type="primary"):

        if not l2_tables:
            st.error("❌ No L2 tables found")
        else:
            # -----------------------------
            # DEMO AGENT LOGIC (mock)
            # -----------------------------
            source_table = l2_tables[0]

            generated_sql = f"""
CREATE OR REPLACE VIEW {database}.{l3_schema}.demo_analytics_view AS
SELECT
    customer_id,
    SUM(amount) AS total_revenue
FROM {database}.{l2_schema}.{source_table}
GROUP BY customer_id;
""".strip()

            st.session_state["generated_sql"] = generated_sql
            st.session_state["view_name"] = "demo_analytics_view"

            st.success("✅ SQL generated by agent")

    st.markdown("#### Available L2 Tables")
    st.write(l2_tables)

# ============================
# RIGHT: SQL + Deploy
# ============================
with col_sql:
    st.markdown("### 📝 Generated SQL")

    sql_text = st.text_area(
        "Review / Edit SQL",
        value=st.session_state.get("generated_sql", ""),
        height=300
    )

    if st.button("🚀 Deploy to L3", type="primary", disabled=not sql_text):
        try:
            session.sql(sql_text).collect()
            st.success("✅ View created successfully in L3")

            st.markdown("### 📊 Preview Output")
            df = session.sql(
                f"SELECT * FROM {database}.{l3_schema}.{st.session_state['view_name']} LIMIT 10"
            ).to_pandas()
            st.dataframe(df)

        except Exception as e:
            st.error(str(e))

# --------------------------------------------------
# Footer
# --------------------------------------------------
st.markdown("---")
st.caption("Snowflake Streamlit Demo | Dataplatr AELT")
